#!/usr/bin/env python3
"""
Per-channel pmax correction factors, derived from the MPV of a Landau fit
to each channel's pmax distribution (same fit as plot_amplitude_map.py,
each channel restricted to the region of the pixel(s) it belongs to).

pmax[1] is the reference channel (factor = 1). Every other channel's
factor is MPV[1] / MPV[channel], meant to be multiplied onto that
channel's pmax values to normalize them onto channel 1's scale.

Writes:
  pmax_correction_factors.json  -- {channel: {"mpv":..., "factor":...}}
  pmax_correction_factors.py    -- importable dict CORRECTION_FACTORS

Usage:
  ./run_root_python.sh compute_pmax_corrections.py [root_file]
"""
import sys
import json
import ROOT

DEFAULT_FILE = "/Volumes/DCRSD_2/TB11/stats_Run5_tracks.root"
REFERENCE_CHANNEL = 1

X_EXPR = "(40*(x_pos1-x_pos2)+x_pos1)"
Y_EXPR = "(40*(y_pos1-y_pos2)+y_pos1)"

PIXEL_CHANNELS = {
    0: (14, 15, 8, 9), 1: (15, 13, 10, 8), 2: (13, 16, 11, 10),
    3: (9, 8, 6, 7), 4: (8, 10, 5, 6), 5: (10, 11, 4, 5),
    6: (7, 6, 2, 3), 7: (6, 5, 1, 2), 8: (5, 4, 12, 1),
}
PIXEL_BOXES = {
    0: (-1.886, -1.391, -1.523, -1.027), 1: (-1.391, -0.903, -1.523, -1.027),
    2: (-0.903, -0.408, -1.523, -1.027), 3: (-1.886, -1.391, -2.014, -1.523),
    4: (-1.391, -0.903, -2.014, -1.523), 5: (-0.903, -0.408, -2.014, -1.523),
    6: (-1.886, -1.391, -2.506, -2.014), 7: (-1.391, -0.903, -2.506, -2.014),
    8: (-0.903, -0.408, -2.506, -2.014),
}

NCHANNELS = 16
NBINS, XLO, XHI = 100, 0, 200

JSON_OUT = "pmax_correction_factors.json"
PY_OUT = "pmax_correction_factors.py"


def channel_to_pixels(channel):
    return sorted(idx for idx, chans in PIXEL_CHANNELS.items() if channel in chans)


def build_cut(pixels):
    parts = []
    for idx in pixels:
        x_lo, x_hi, y_lo, y_hi = PIXEL_BOXES[idx]
        parts.append(f"({X_EXPR}>{x_lo} && {X_EXPR}<{x_hi} && {Y_EXPR}>{y_lo} && {Y_EXPR}<{y_hi})")
    return "(" + " || ".join(parts) + ")"


def fit_mpv(tree, channel):
    pixels = channel_to_pixels(channel)
    cut = build_cut(pixels)
    hname = f"h_pmax{channel}"
    tree.Draw(f"pmax[{channel}]>>{hname}({NBINS},{XLO},{XHI})", cut, "goff")
    h = ROOT.gDirectory.Get(hname)
    fit = ROOT.TF1(f"flandau{channel}", "landau", XLO, XHI)
    h.Fit(fit, "Q")
    return fit.GetParameter(1), fit.GetParError(1)


def main():
    root_file = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FILE

    f = ROOT.TFile.Open(root_file)
    if not f or f.IsZombie():
        sys.exit(f"Could not open {root_file}")
    tree = f.Get("Analysis")

    mpv = {}
    for ch in range(1, NCHANNELS + 1):
        mpv[ch], mpv_err = fit_mpv(tree, ch)
        print(f"pmax[{ch}]: MPV = {mpv[ch]:.3f} +/- {mpv_err:.3f}")

    ref_mpv = mpv[REFERENCE_CHANNEL]
    factors = {ch: ref_mpv / mpv[ch] for ch in mpv}

    print(f"\nCorrection factors (reference: pmax[{REFERENCE_CHANNEL}], factor=1):")
    for ch in range(1, NCHANNELS + 1):
        print(f"  channel {ch:2d}: factor = {factors[ch]:.5f}")

    data = {
        "reference_channel": REFERENCE_CHANNEL,
        "channels": {
            str(ch): {"mpv": mpv[ch], "factor": factors[ch]} for ch in range(1, NCHANNELS + 1)
        },
    }
    with open(JSON_OUT, "w") as fp:
        json.dump(data, fp, indent=2)
    print(f"\nSaved {JSON_OUT}")

    with open(PY_OUT, "w") as fp:
        fp.write('"""Per-channel pmax correction factors (generated by compute_pmax_corrections.py).\n\n')
        fp.write(f"Reference channel: pmax[{REFERENCE_CHANNEL}] (factor = 1.0).\n")
        fp.write("Multiply a channel's pmax value by its factor to normalize onto the\n")
        fp.write("reference channel's scale.\n\"\"\"\n\n")
        fp.write("CORRECTION_FACTORS = {\n")
        for ch in range(1, NCHANNELS + 1):
            fp.write(f"    {ch}: {factors[ch]:.5f},\n")
        fp.write("}\n")
    print(f"Saved {PY_OUT}")


if __name__ == "__main__":
    main()
