"""Per-channel pmax correction factors (generated by compute_pmax_corrections.py).

Reference channel: pmax[1] (factor = 1.0).
Multiply a channel's pmax value by its factor to normalize onto the
reference channel's scale.
"""

CORRECTION_FACTORS = {
    1: 1.00000,
    2: 0.92706,
    3: 1.02323,
    4: 1.20169,
    5: 0.88111,
    6: 0.77793,
    7: 1.01934,
    8: 0.89452,
    9: 1.02040,
    10: 0.93071,
    11: 1.41083,
    12: 1.17702,
    13: 1.05885,
    14: 1.20560,
    15: 1.30564,
    16: 1.22345,
}
